config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'teams#index'

  resources :tournaments, only: [:index] do
    member do
      post :register_team
      post :withdraw_team
    end
  end

  resources :teams, except: [:show]

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy', as: :sign_out
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: players
#
#  id            :integer          not null, primary key
#  team_id       :integer
#  tournament_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Player < ApplicationRecord
  belongs_to :team
  belongs_to :tournament

  validates :team_id,       uniqueness: { scope: %i[team_id tournament_id] }
  validates :tournament_id, uniqueness: { scope: %i[team_id tournament_id] }
end

app/models/team.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  logo       :string
#

class Team < ApplicationRecord

  scope :in_tournament, ->(tournament) { tournament.teams }

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :players, dependent: :destroy
  has_many :tournaments, through: :players

  validates :name, presence: true, uniqueness: true

  mount_uploader :logo, TeamLogoUploader
end

app/models/tournament.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string
#

class Tournament < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :teams, through: :players

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nick       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  uid        :integer
#

class User < ApplicationRecord
  has_one :team, dependent: :destroy

  validates :nick, presence: true
  validates :uid, presence: true

  def self.find_or_create_from_omniauth(auth)
    find_or_create_by(uid: auth.uid) do |user|
      user.nick  = auth.info.nick
      user.email = auth.info.email
    end
  end

  def to_s
    nick
  end

  ##
  # Whether user has a team and particularly this team if the argument is provided.
  #
  # @param [Team] team
  # @return [Boolean]
  #
  def owns_team?(team = nil)
    team ? self.team == team : self.team.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :current_user_owns_team?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def current_user_owns_team?(team = nil)
    logged_in? && current_user.owns_team?(team)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Signed in'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  before_action :set_team, only: %i[edit update destroy]
  before_action :set_tournament, only: [:index]
  before_action :check_user, only: %i[new create edit update destroy]

  def index
    @teams = @tournament ? Team.in_tournament(@tournament) : Team.all
  end

  def new
    @team = current_user.build_team
  end

  def edit; end

  def create
    @team = current_user.build_team(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_path, notice: 'Successfully created' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to teams_path, notice: 'Successfully updated' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Successfully destroyed' }
    end
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def set_tournament
    @tournament = params[:tournament_id].present? ? Tournament.find(params[:tournament_id]) : nil
  end

  def check_user
    if !logged_in? || creating_another_team? || editing_another_team?
      redirect_to root_path, notice: 'You have no permission for this action!'
    end
  end

  ##
  # User already has a team and creates new one.
  #
  def creating_another_team?
    %w[new create].include?(action_name) && current_user.owns_team?
  end

  ##
  # User editing team which he does not own.
  #
  def editing_another_team?
    %w[edit update destroy].include?(action_name) && (current_user.team.try(:id) != params[:id].to_i)
  end

  def team_params
    params.require(:team).permit(:name, :team_id, :logo, :tournament_id)
  end
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[register_team withdraw_team]
  before_action :set_team,       only: %i[register_team withdraw_team]
  before_action :check_user,     only: %i[register_team withdraw_team]

  def index
    @tournaments = Tournament.all
  end

  def register_team
    @tournament.teams << @team

    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Successfully registered' }
    end
  end

  def withdraw_team
    @tournament.teams.destroy(@team)

    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Successfully withdrawn' }
    end
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def set_team
    @team = Team.find(params[:team_id])
  end

  def check_user
    unless current_user_owns_team?(@team)
      redirect_to tournaments_path, notice: 'You have no permission for this action!'
    end
  end

  def tournament_params
    params.fetch(:tournament, {})
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_flash_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def datetime_formatter(datetime)
    datetime.strftime('%e %B %Y, %R')
  end
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/views/layouts/_footer.html.erb
<!--  Footer  -->
  <div class='footer'>
      <%= link_to image_tag('starladder_logo.png', alt: "Starladder logo", class: 'footer-logo'), '/' %>
      <p class='footer-copyright-text'>
        Copyright © 2012 - 2018 Starladder LLC. All rights reserved
      </p>
  </div>

app/views/layouts/_header.html.erb
<!-- Default navbar -->
   <nav class="navbar navbar-default">
     <div class="container">
       <div class="navbar-header">

         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <%= link_to image_tag('starladder_logo.png', alt: "Starladder logo", class: 'navbar-logo'), '/' %>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav navbar-left">
           <li class="<%= current_page?(controller: 'teams', action: 'index') %>">
             <%= link_to 'Home', teams_path %>
           </li>
           <li class="<%= current_page?(controller: 'tournaments', action: 'index') %>">
             <%= link_to 'Tournaments', tournaments_path %>
           </li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
            <% if !logged_in? %>
              <li>
                <%= link_to t('layouts.application.sign_in'), '/auth/starladder' %>
              </li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.nick %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#">Profile</a></li>
                  <!--TODO: Add users profile page-->
                  <li>
                    <%= link_to t('layouts.application.sign_out'), sign_out_path %>
                  </li
                </ul>
              </li>
            <% end %>
         </ul>
       </div>
     </div>
   </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
    <%= favicon_link_tag 'favicons.png' %>
    <title>
      <%= TITLE %>
    </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row" style='min-height: 450px'>
        <%= render partial: 'shared/flash', flash: flash %>
        <%= yield %>
      </div>
    </div>
    <footer>
    <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_flash_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/tournaments/_tournament.html.erb
<% tournament_teams = tournament.teams %>
<div class="col-md-3" id="tournament-<%= tournament.id %>">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4 class="media-heading">
        <%= tournament.name %>
      </h4>
      <span aria-hidden="true" class="glyphicon glyphicon-user"></span>
      <% teams_number = tournament_teams.count %>
      <% if teams_number.zero? %>
        No teams registered yet
      <% else %>
        <%= link_to "#{teams_number} #{'team'.pluralize(teams_number)} registered", teams_path(tournament_id: tournament.id) %>
      <% end %>
      <br/>
      <% if current_user_owns_team? %>
        <div class="pull-right">
          <% if tournament_teams.include?(current_user.team) %>
            <%= link_to 'Withdraw', withdraw_team_tournament_path(tournament, team_id: current_user.team.id), method: :post, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
          <% else %>
            <%= link_to 'Register', register_team_tournament_path(tournament, team_id: current_user.team.id), method: :post, remote: true, class: 'btn btn-primary btn-xs' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tournaments/index.html.erb
<h1>Tournaments</h1>
<br/>
<% if @tournaments.blank? %>
  No tournaments for the moment!
<% else %>
  <% @tournaments.each do |tournament| %>
    <%= render 'tournament', tournament: tournament %>
  <% end %>
<% end %>
<br/>